<?php

namespace Cannibal\Bundle\NameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * Genericsitory methods below.
 */
class NameRepository extends EntityRepository
{
}